### ISSUE TITLE
How correctly reorgonize files in environment folder? | ImproperlyConfigured

### ISSUE THREAD

**Issue by NogerbekNurzhan** [sobolevn/django-split-settings#34]
I am trying to use you application in my project but it raise error:
```
ImproperlyConfigured: settings.DATABASES is improperly configured.
Please supply the ENGINE value.
Check settings documentation for more details.
```

**P.S.** Database settings are correct. With next settings I can run project with `python manage.py runserver` command without any problem. Error happens when user try to go to any link of the project. It seems to me that I reorgonize `development.py` file (which inside environment folder) incorrect. Can you give me some advice, please? I tested right now and notice that if I set  `'components/database_developemnt.py'` in `base_settings `of `__init__.py` file, it works fine. But as you can see from the structure below I have 2 database settings file. One for development and one fore production.

I use:
```
Django 1.11
Python 2.7
```

**structure:**
```
project_name/settings/
    __init__.py
    components
        __init__.py
        common.py
        secret_key.py
        database_development.py
        database_production.py
    environments
        __init__.py
        development.py
        production.py
```

**__ init __.py:**
```
# -*- coding: utf-8 -*-

from split_settings.tools import include
from os import environ

ENVIRONMENT = 'development' or 'production'

base_settings = [
    'components/common.py',  # Common settings which I use in development and in production
    'components/secret_key.py',  # Secret key of the project which generated by Django

    'environments/%s.py' % ENVIRONMENT,
]

include(*base_settings)
```
**database_development.py:**
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'NAME',
        'USER': 'USER',
        'PASSWORD': 'PASSWORD',
    }
}
```

**development.py:**
```
from split_settings.tools import include, optional

DEBUG = True

development_settings = [
    optional('components/database_development.py'),  # Database for development
    optional('components/logging.py'),  # Logging in developement
]

include(*development_settings)
```

**ERROR:**
```
Traceback (most recent call last):
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
response = get_response(request)
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
if test_func(request.user):
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 46, in <lambda>
lambda u: u.is_authenticated,
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/utils/functional.py", line 238, in inner
self._setup()
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/utils/functional.py", line 386, in _setup
self._wrapped = self._setupfunc()
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 24, in <lambda>
request.user = SimpleLazyObject(lambda: get_user(request))
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 12, in get_user
request._cached_user = auth.get_user(request)
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 211, in get_user
user_id = _get_user_session_key(request)
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 61, in _get_user_session_key
return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 57, in __getitem__
return self._session[key]
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 207, in _get_session
self._session_cache = self.load()
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 35, in load
expire_date__gt=timezone.now()
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/db/models/query.py", line 374, in get
num = len(clone)
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/db/models/query.py", line 232, in __len__
self._fetch_all()
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
self._result_cache = list(self._iterable_class(self))
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 876, in execute_sql
sql, params = self.as_sql()
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 428, in as_sql
extra_select, order_by, group_by = self.pre_sql_setup()
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 46, in pre_sql_setup
self.setup_query()
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 37, in setup_query
self.select, self.klass_info,
self.annotation_col_map = self.get_select()
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 227, in get_select
sql, params = self.compile(col, select_format=True)
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 373, in compile
sql, params = node.as_sql(self, self.connection)
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/db/models/expressions.py", line 695, in as_sql
return "%s.%s" % (qn(self.alias), qn(self.target.column)), []
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 364, in quote_name_unless_alias
r = self.connection.ops.quote_name(name)
File "/Users/nurzhan_nogerbek/Virtualenvs/py2714/lib/python2.7/site-packages/django/db/backends/dummy/base.py", line 20, in complain
raise ImproperlyConfigured("settings.DATABASES is improperly configured. "
ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
```

**Comment by sobolevn** [comment]
I would say that there is a problem with your structure.
Have a look at this example: https://github.com/wemake-services/wemake-django-template/tree/master/%7B%7Bcookiecutter.project_name%7D%7D/server/settings

And check out the whole template, maybe you will find it useful.

**Comment by NogerbekNurzhan** [comment]
I tried to make the similar structure as you described in your article. I just thought that it would be better to  put confidential data to separate files (in my case database_development.py, secret_key.py etc). After that it will be easy don't use them in version control system. What do you think about that?

From that link which you send me I notice that database settings in `common.py` file but in the same time you use autoconfig application, isn't it? Is it possible to set it without any additional dependency? I am so confused =(

Some explanations would clarify the situation for me.

**Comment by sobolevn** [comment]
There is no need in putting secret settings into some specific files that are ignored.
Just don't put these settings into `python` files at all.

I am using `autoconf` for this task, but you can use `os.environ` instead.
